# Generated by Django 4.2.27 on 2026-01-08 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astromall', '0004_order_status_alter_cartitem_id_alter_category_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
