# Generated by Django 6.0 on 2026-01-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrologers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='astrologerprofile',
            old_name='price_per_minute',
            new_name='chat_price_per_minute',
        ),
        migrations.AddField(
            model_name='astrologerprofile',
            name='call_price_per_minute',
            field=models.DecimalField(decimal_places=2, default=15.0, max_digits=6),
        ),
    ]
