# Generated by Django 4.2.27 on 2026-01-06 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrologers', '0002_rename_price_per_minute_astrologerprofile_chat_price_per_minute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='astrologerprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='astrologerprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='language',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
