# Generated by Django 4.2.27 on 2026-01-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astrologers', '0003_astrologerprofile_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astrologerprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='language',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='skill',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
