# Generated by Django 6.0 on 2026-01-05 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='consultation_type',
            field=models.CharField(choices=[('chat', 'Chat'), ('call', 'Call')], default='chat', max_length=10),
        ),
    ]
