# Generated by Django 6.0 on 2026-01-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='proposed_reschedule_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('reschedule_proposed', 'Reschedule Proposed')], default='pending', max_length=20),
        ),
    ]
