# Generated by Django 4.2.27 on 2026-01-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0006_alter_booking_id_alter_chatmessage_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatsession',
            name='actual_start_time',
            field=models.DateTimeField(blank=True, help_text='Time when astrologer sends first message', null=True),
        ),
    ]
