# Generated by Django 6.0 on 2026-01-04 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZodiacSign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='zodiac_images/')),
            ],
        ),
        migrations.CreateModel(
            name='DailyHoroscope',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('sign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_horoscopes', to='horoscope.zodiacsign')),
            ],
            options={
                'unique_together': {('sign', 'date')},
            },
        ),
    ]
