# Generated by Django 4.2.27 on 2026-01-25 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horoscope', '0002_alter_dailyhoroscope_id_alter_zodiacsign_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyhoroscope',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='zodiacsign',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
